/** Имя в каталоге awg на хосте и в `/etc/wireguard` внутри контейнера. */
export const PANEL_WG_NAT_SCRIPT_BASENAME = "panel-nat.sh";

/**
 * FORWARD / DOCKER-USER — **iptables-legacy** (как у Docker на Ubuntu).
 * SNAT: **nft** — `iifname` туннеля (в POSTROUTING допустимо). **iptables (nf_tables)** — только **`-o WAN`**
 * (`default dev`), без **`-i`** в POSTROUTING (`Can't use -i with POSTROUTING` в v1.8.x nft backend).
 * Сообщение `iptables-legacy tables present` у `iptables -L` — предупреждение ядра, не выбор legacy для NAT.
 */
export function buildPanelWgNatScript(): string {
  return [
    "#!/bin/sh",
    "# amnesia-veb: NAT и FORWARD для клиентов VPN.",
    "# compose: network_mode host, pid host, privileged.",
    "set -eu",
    "ACTION=${1:?}",
    "IFACE=${2:?}",
    "SUBNET=${3:?}",
    "",
    "run_ipt() {",
    "  if command -v nsenter >/dev/null 2>&1 && nsenter -t 1 -m test -x /usr/sbin/iptables-legacy 2>/dev/null; then",
    "    nsenter -t 1 -m -- /usr/sbin/iptables-legacy \"$@\"",
    "    return",
    "  fi",
    "  if command -v nsenter >/dev/null 2>&1 && nsenter -t 1 -m test -x /sbin/iptables-legacy 2>/dev/null; then",
    "    nsenter -t 1 -m -- /sbin/iptables-legacy \"$@\"",
    "    return",
    "  fi",
    "  if command -v iptables-legacy >/dev/null 2>&1; then",
    "    iptables-legacy \"$@\"",
    "    return",
    "  fi",
    "  iptables \"$@\"",
    "}",
    "",
    "nft_nat_chain() {",
    "  for c in postrouting POSTROUTING; do",
    "    if nft list chain ip nat \"$c\" >/dev/null 2>&1; then",
    "      printf %s \"$c\"",
    "      return 0",
    "    fi",
    "  done",
    "  return 1",
    "}",
    "",
    "nft_masq_up() {",
    "  command -v nft >/dev/null 2>&1 || return 1",
    "  CH=$(nft_nat_chain) || return 1",
    "  if nft -a list chain ip nat \"$CH\" 2>/dev/null | grep -F \"iifname\" | grep -F \"$IFACE\" | grep -q masquerade; then",
    "    return 0",
    "  fi",
    "  nft insert rule ip nat \"$CH\" position 0 iifname \"$IFACE\" ip daddr != \"$SUBNET\" masquerade",
    "}",
    "",
    "nft_masq_down() {",
    "  command -v nft >/dev/null 2>&1 || return 0",
    "  CH=$(nft_nat_chain) || return 0",
    "  while true; do",
    "    h=$(nft -a list chain ip nat \"$CH\" 2>/dev/null | grep masquerade | grep -F \"ip saddr $SUBNET\" | sed -n 's/.*# handle \\([0-9][0-9]*\\).*/\\1/p' | head -n1)",
    "    case \"$h\" in ''|*[!0-9]*) break ;; esac",
    "    nft delete rule ip nat \"$CH\" handle \"$h\" 2>/dev/null || break",
    "  done",
    "  while true; do",
    "    h=$(nft -a list chain ip nat \"$CH\" 2>/dev/null | grep masquerade | grep -F \"iifname\" | grep -F \"$IFACE\" | sed -n 's/.*# handle \\([0-9][0-9]*\\).*/\\1/p' | head -n1)",
    "    case \"$h\" in ''|*[!0-9]*) break ;; esac",
    "    nft delete rule ip nat \"$CH\" handle \"$h\" 2>/dev/null || break",
    "  done",
    "}",
    "",
    "wan_dev4() {",
    "  ip -4 route show default 2>/dev/null | awk '/^default/ { print $5; exit }'",
    "}",
    "",
    'case "$ACTION" in',
    "up)",
    "  sysctl -w net.ipv4.ip_forward=1 2>/dev/null || true",
    '  sysctl -w "net.ipv4.conf.$IFACE.rp_filter=0" 2>/dev/null || true',
    '  run_ipt -C FORWARD -i "$IFACE" -j ACCEPT 2>/dev/null || run_ipt -I FORWARD 1 -i "$IFACE" -j ACCEPT',
    '  run_ipt -C FORWARD -o "$IFACE" -j ACCEPT 2>/dev/null || run_ipt -I FORWARD 1 -o "$IFACE" -j ACCEPT',
    '  run_ipt -C DOCKER-USER -i "$IFACE" -j RETURN 2>/dev/null || run_ipt -I DOCKER-USER 1 -i "$IFACE" -j RETURN 2>/dev/null || true',
    '  run_ipt -C DOCKER-USER -o "$IFACE" -j RETURN 2>/dev/null || run_ipt -I DOCKER-USER 1 -o "$IFACE" -j RETURN 2>/dev/null || true',
    "  nft_masq_down",
    "  if ! nft_masq_up; then",
    '    echo "panel-nat: nft masquerade (iifname) skipped or failed" >&2',
    "  fi",
    "  WAN_DEV=$(wan_dev4)",
    '  if nsenter -t 1 -m test -x /usr/sbin/iptables 2>/dev/null; then',
    '    while nsenter -t 1 -m -- /usr/sbin/iptables -t nat -D POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -j MASQUERADE 2>/dev/null; do :; done',
    '    while nsenter -t 1 -m -- /usr/sbin/iptables -t nat -D POSTROUTING -i "$IFACE" ! -o "$IFACE" -j MASQUERADE 2>/dev/null; do :; done',
    '    if [ -n "$WAN_DEV" ]; then',
    '      while nsenter -t 1 -m -- /usr/sbin/iptables -t nat -D POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -o "$WAN_DEV" -j MASQUERADE 2>/dev/null; do :; done',
    '      nsenter -t 1 -m -- /usr/sbin/iptables -t nat -C POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -o "$WAN_DEV" -j MASQUERADE 2>/dev/null || nsenter -t 1 -m -- /usr/sbin/iptables -t nat -I POSTROUTING 1 -s "$SUBNET" ! -d "$SUBNET" -o "$WAN_DEV" -j MASQUERADE',
    "    else",
    '      echo "panel-nat: no IPv4 default route dev; NAT without -o (may not match on nft)" >&2',
    '      nsenter -t 1 -m -- /usr/sbin/iptables -t nat -C POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -j MASQUERADE 2>/dev/null || nsenter -t 1 -m -- /usr/sbin/iptables -t nat -I POSTROUTING 1 -s "$SUBNET" ! -d "$SUBNET" -j MASQUERADE',
    "    fi",
    "  fi",
    "  ;;",
    "down)",
    "  nft_masq_down",
    "  WAN_DEV=$(wan_dev4)",
    '  while run_ipt -t nat -D POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -j MASQUERADE 2>/dev/null; do :; done',
    '  while run_ipt -t nat -D POSTROUTING -i "$IFACE" ! -o "$IFACE" -j MASQUERADE 2>/dev/null; do :; done',
    '  if [ -n "$WAN_DEV" ]; then',
    '    while run_ipt -t nat -D POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -o "$WAN_DEV" -j MASQUERADE 2>/dev/null; do :; done',
    "  fi",
    "  if command -v nsenter >/dev/null 2>&1 && nsenter -t 1 -m test -x /usr/sbin/iptables 2>/dev/null; then",
    '    while nsenter -t 1 -m -- /usr/sbin/iptables -t nat -D POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -j MASQUERADE 2>/dev/null; do :; done',
    '    while nsenter -t 1 -m -- /usr/sbin/iptables -t nat -D POSTROUTING -i "$IFACE" ! -o "$IFACE" -j MASQUERADE 2>/dev/null; do :; done',
    '    if [ -n "$WAN_DEV" ]; then',
    '      while nsenter -t 1 -m -- /usr/sbin/iptables -t nat -D POSTROUTING -s "$SUBNET" ! -d "$SUBNET" -o "$WAN_DEV" -j MASQUERADE 2>/dev/null; do :; done',
    "    fi",
    "  fi",
    '  while run_ipt -D DOCKER-USER -o "$IFACE" -j RETURN 2>/dev/null; do :; done',
    '  while run_ipt -D DOCKER-USER -i "$IFACE" -j RETURN 2>/dev/null; do :; done',
    '  while run_ipt -D FORWARD -o "$IFACE" -j ACCEPT 2>/dev/null; do :; done',
    '  while run_ipt -D FORWARD -i "$IFACE" -j ACCEPT 2>/dev/null; do :; done',
    '  sysctl -w "net.ipv4.conf.$IFACE.rp_filter=2" 2>/dev/null || true',
    "  ;;",
    "*)",
    '  echo "panel-nat: usage: up|down <iface> <cidr>" >&2',
    "  exit 1",
    "  ;;",
    "esac",
  ].join("\n");
}
